name: 'CI'

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Build CI container
        run: 'docker build -t maruos/blueprints/ci --file Dockerfile.aarch64 .'
      - name: fix permissions
        run: 'sudo chown -R root:root $(pwd)/blueprint/debian/debpkg && sudo chmod -R 0755 $(pwd)/blueprint/debian/debpkg'
      - name: Build Debian bookworm arm64
        run: 'docker run --privileged --rm -v /var/cache:/var/cache -v "$(pwd)":/var/maru -i maruos/blueprints/ci -b debian -n debian -- -r bookworm -a arm64'
      - name: Upload generated rootfs tarball
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bookworm-container-arm64
          path: out/*.tar.gz
